backend:
  # Pick repo to use, use test repo for netlifyCMS development

  name: git-gateway
  # name: test-repo

  branch: master

# Uncomment to allow editorial workflow
# publish_mode: editorial_workflow

media_folder: "src/assets/img"
public: "_includes/assets/img"

collections:
  # settings in _data
  - name: "settings"
    label: "Pengaturan"
    files: 
      - name: "metadata"
        label: "Metadata"
        file: "src/_data/metadata.json"
        fields:
          - {name: title, label: Nama website, widget: string}
          - {name: url, label: Url, widget: string}
          - name: author
            label: Pemilik website
            widget: object
            fields:
              - {name: name, label: Nama, widget: string}
              - {name: email, label: Email, widget: string}
              - {name: github, label: Github, widget: string}
          - {name: brand_logo, label: Logo, widget: image}
      
      # - name: "homepage"
      #   label: "Halaman"
      #   file: "src/_data/pages/home.json"
      #   fields:
      #     - 

  # posts in /posts/
  - name: "info" # Used in routes, e.g., /admin/collections/blog
    label: "Info" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal terbit", name: "date", widget: "datetime" }
      - { label: "Kutipan", name: "excerpt", widget: "text" }
      - { label: "Label", name: "tags", widget: "list", default: ["post"] }
      - { label: "Konten", name: "body", widget: "markdown" }

  # Pages in /pages/
  - name: "pages"
    label: "Halaman"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal terbit", name: "date", widget: "datetime" }
      - { label: "Kutipan", name: "excerpt", widget: "text" }
      - { label: "Label", name: "tags", widget: "list", default: ["post"] }
      - { label: "Konten", name: "body", widget: "markdown" }

  # Fundraises in /fundraises/
  - name: "fundraises"
    label: "Penggalangan Dana"
    folder: "src/fundraises"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal terbit", name: "date", widget: "datetime" }
      - { label: "Kutipan", name: "excerpt", widget: "text" }
      - label: "Penggalangan Dana"
        name: "fra"
        widget: "object"
        fields:
          - { label: "Target ditentukan", name: "hasTarget", widget: "boolean", default: true }
          - { label: "Target", name: "target", widget: "number", default: "5000000" }
          - { label: "Terkumpul", name: "raised", widget: "number", default: "2000000"}
      - label: "Spanduk"
        name: "banner"
        widget: "object"
        fields :
          - { label: "Gambar", name: "image", widget: "image", allow_multiple: false }
          - { label: "Gaya", name: "style", widget: "select", options: [ "contain", "cover" ], default: "contain" }
      - { label: "Label", name: "tags", widget: "list" }
      - { label: "Konten", name: "body", widget: "markdown" }
